; This file was auto-generated by drush make
core = 8.x
api = 2

; Core
; Modules
projects[admin_toolbar][subdir] = "contrib"
projects[admin_toolbar][version] = "1.14"

projects[composer_manager][subdir] = "contrib"
projects[composer_manager][branch] = "1.x-dev"
projects[composer_manager][revision] = "b5da8d1"

projects[clutch][subdir] = "custom"
projects[clutch][download][type] = "git"
projects[clutch][download][url] = "git@github.com:poetic/clutch.git"
projects[clutch][download][branch] = "features/refactor-find-and-replace"
projects[clutch][download][working-copy] = "1"

projects[coffee][subdir] = "contrib"
projects[coffee][version] = "1.0-beta1"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "3.x-dev"

projects[devel][subdir] = "contrib"
projects[devel][download][branch] = "1.x-dev"
projects[devel][download][revision] = "c0b5c5f"
projects[devel][download][type] = "git"

projects[entity_reference_revisions][subdir] = "contrib"
projects[entity_reference_revisions][version] = "1.0-rc4"

projects[facets][subdir] = "contrib"
projects[facets][version] = "1.0-alpha1"

projects[linkit][subdir] = "contrib"
projects[linkit][version] = "4.1"

projects[metatag][subdir] = "contrib"
projects[metatag][version] = "1.0-beta4"

projects[migrate_plus][subdir] = "contrib"
projects[migrate_plus][version] = "1.0-beta1"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.0-alpha2"

projects[paragraphs][subdir] = "contrib"
projects[paragraphs][version] = "1.0-rc4"

projects[s3fs][subdir] = "contrib"
projects[s3fs][version] = "2.x-dev"

projects[search_api][subdir] = "contrib"
projects[search_api][version] = "1.0-alpha12"

projects[token][subdir] = "contrib"
projects[token][version] = "1.0-alpha2"

