; This file was auto-generated by drush make
core = 8.x
api = 2

; Core
; Modules
projects[admin_toolbar][subdir] = "contrib"
projects[admin_toolbar][version] = "1.14"

projects[composer_manager][subdir] = "contrib"
projects[composer_manager][branch] = "1.x-dev"
projects[composer_manager][revision] = "b5da8d1"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "3.x-dev"

projects[devel][subdir] = "contrib"
projects[devel][download][branch] = "1.x-dev"
projects[devel][download][revision] = "c0b5c5f"
projects[devel][download][type] = "git"

projects[entity_reference_revisions][subdir] = "contrib"
projects[entity_reference_revisions][version] = "1.0-rc4"

projects[metatag][subdir] = "contrib"
projects[metatag][version] = "1.0-beta4"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.0-alpha1"

projects[paragraphs][subdir] = "contrib"
projects[paragraphs][version] = "1.0-rc4"

projects[token][subdir] = "contrib"
projects[token][version] = "1.0-alpha2"

